export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userContants = {
  ADD_USER_REQUEST: 'ADD_USER_REQUEST',
  ADD_USER_FAILURE: 'ADD_USER_FAILURE',
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',

  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',

  VIEW_USER_REQUEST: 'VIEW_USER_REQUEST',
  VIEW_USER_FAILURE: 'VIEW_USER_FAILURE',
  VIEW_USER_SUCCESS: 'VIEW_USER_SUCCESS',

  VIEW_ALL_USER_REQUEST: 'VIEW_ALL_USER_REQUEST',
  VIEW_ALL_USER_FAILURE: 'VIEW_ALL_USER_FAILURE',
  VIEW_ALL_USER_SUCCESS: 'VIEW_ALL_USER_SUCCESS',

  RESET_STATE: 'RESET_STATE',
}

export const postContants = {
  ADD_POST_REQUEST: 'ADD_POST_REQUEST',
  ADD_POST_FAILURE: 'ADD_POST_FAILURE',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',

  DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
  DELETE_POST_FAILURE: 'DELETE_POST_FAILURE',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',

  VIEW_POST_REQUEST: 'VIEW_POST_REQUEST',
  VIEW_POST_FAILURE: 'VIEW_POST_FAILURE',
  VIEW_POST_SUCCESS: 'VIEW_POST_SUCCESS',

  VIEW_ALL_POST_REQUEST: 'VIEW_ALL_POST_REQUEST',
  VIEW_ALL_POST_FAILURE: 'VIEW_ALL_POST_FAILURE',
  VIEW_ALL_POST_SUCCESS: 'VIEW_ALL_POST_SUCCESS',

  RESET_STATE: 'RESET_STATE',
}
